### ISSUE TITLE
Administration Options + UAA Incompatible

### ISSUE THREAD

**Issue by ruddell** [jhipster/jhipster-registry#148]
##### **Overview of the issue**

With non-UAA services, when I view any of the pages under the Administration dropdown (Metrics, Health, Config, Logs), it works beautifully.  Great work - I'm impressed with what it can do!  It's a much improved microservice workflow.

With UAA services, when I choose the service from the dropdown, I receive a 401 error triggering the interceptor and am logged out.

##### **Reproduce the error**
 - Start the registry and a UAA.  
 - Navigate to any choice under the Administration dropdown
 - Choose the UAA service in the dropdown
    - You will be logged out and the only option in the navbar is to go home and login.

##### **JHipster Version(s)**
v4.5.3 of generator-jhipster (master)
v3.0.1 of jhipster-registry

##### **JHipster configuration**
Default UAA
<details>
  <summary>Click to see config</summary>

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.3",
    "baseName": "uaa",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "e3a02c2ac15a706364ec28e0c52bc90967e92131",
    "enableTranslation": true,
    "applicationType": "uaa",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn"
  }
}
```

</details>

**Comment by deepu105** [comment]
ping @xetys

**Comment by xetys** [comment]
I'll take a look asap

**Comment by xetys** [comment]
Ok, this is a bigger issue I see. The registry assumes the applications are always secured using JWT, so just generates an own JWT using the shared secret key and tries to fetch the endpoints. 

The UAA way of this would be if the UAA holds a client credentials OAuth client, which has the proper permissions. In my understanding, I would then secure the metrics by scope, rather than roles, as OAuth allows us to use distinct roles for human access and service access.

Afterward, the registry should know if security is done via OAuth or using JWT. I suggest doing this step together with https://github.com/jhipster/generator-jhipster/pull/5812.

**Comment by xetys** [comment]
I have some thoughts about using client credentials grant for this page...I
will put that on my to-do to find a solution here

Julien Dubois <notifications@github.com> schrieb am Do., 19. Okt. 2017,
18:06:

**Comment by jdubois** [comment]
This is solved for OpenID Connect - I don't know UAA well enough, but now that should be easier (and @xetys I can help)

**Comment by jearton** [comment]
I am involved in the same problem using JHipster 4.11.1. 

Is there a step-by-step solution?

I'm a beginner with security.

**Comment by matthewdfleming** [comment]
Two of the three major functions (Eureka server, cloud config server) work great irrespective of the security for the application instances. 

Any ideas or comments about how to make the 'administration server' functionality work with UAA secured applications? It seems like I can either add UAA token support to the Registry or add JWT support to each application.. any thoughts about which rabbit hole might be shorter?

**Comment by jdubois** [comment]
For me the solution would be to add UAA token support to the Registry. It's probably not very hard, as the Registry is in fact a JHipster application, so you would need to copy the security config of a working application and port it to the Registry.

**Comment by jdubois** [comment]
No, that's why the ticket is still opened.
There are a lot of things changing for OAuth2 support with JHipster 5 (coming from Spring Security 5), which should make things easier, but that's also a lot of work for us.

**Comment by behrad84** [comment]
@jdubois I see, the reason I asked is that I saw latest commit in develop branch but it didn’t resolve the issue ! Thank you

**Comment by pascalgrimaud** [comment]
@behrad84 : the last weeks, I worked a lot on jhipster-registry, specially with the migration to Spring Boot 2 and Angular5. It should work for JWT and OAuth2, but I don't know UAA at all, and as I didn't touch the code for UAA, I think it's broken with this option.

So for me:
- if someone can work on this before the JHipster 5, it will be really welcome
- otherwise, I think, we should hide the UAA option, as it is useless to propose an option which doesn't work

Ping @xetys as you are the main author of this part

**Comment by rifatdover** [comment]
I think this is because of a cyclic dependency within uaa and registery server which is also I'am facing now. When authentication used with uaa all authentication work is done over uaa. And becasue uaa is also a microservice it needs to register itself to registery. You can use other authentication methods like JWT or Keycloack authentication over registery and UAA OAtuh2 within microservices but this is also making registery impossible to authenticate to microservices which needs it for administration features. In the end administration features not working because of this dependency. Maybe registery will authenticate with an authorization code to microservices and its authentication need to be independent form UAA and will use this code for authentication.

**Comment by rifatdover** [comment]
But what I believe it will be nice if UAA will only be a OpenID Connect Resource Provider for Keycloack. But this will make UAA mandatory to use Keycloack. 
http://www.keycloak.org/docs/3.2/securing_apps/topics/oidc/oidc-overview.html

**Comment by rifatdover** [comment]
Will you check if it is ok in PR #261 ?

**Comment by jdubois** [comment]
@rifatdover your PR has more than 2,500 new lines of code, so that will probably take time, but yes it's very important we support UAA

**Comment by rifatdover** [comment]
All of them are based on generated Gateway project or microservices project code @jdubois I did not write them all :) What is you need to be careful is security configurations, application configurations and authentication order permits. But of course, you should take a look.

**Comment by rifatdover** [comment]
I did some manual rebase for develop branch created #262 This PR beneath every change inside #261 but bases develop branch

**Comment by xetys** [comment]
I took a look at this, and first, sorry for the incredible delay from my side.

So far, @rifatdover thanks for your contribution, I checked it out. Unfortunately, that's not the way I think it's correct. In short: this problem is a use-case for the service-to-service communication using UAA. The registry has an own and simple user management, which doesn't relate to the user's domain representation of a user. Changing this to UAA being responsible for the users needed for JHipster registry, forces to keep a user record for that. That's not the OAuth way.

When using UAA, JHipster automatically generates a second OAuth client called "internal". Currently, this client gets only the scope "web-app". But you can add `authorities("ROLE_ADMIN")`, and it gets possible to read all the microservices' endpoints out of the box (the more accurate would be to change all microservices security configuration to `hasRole('ADMIN') or hasScope('management')`, but would force to touch all microservices). After this, the registry must authorize using client credentials grant with the 'internal' client and use its token for forwarded requests to all microservices.

In fact, that's not hard to do, it's just a filter which adds an OAuth2 access token to all those requests.

You can see how it works in #262. If that solution is ok, I would prefer this. WDYT?

**Comment by rifatdover** [comment]
@xetys I understand what you do. But I don't know if it is right to give internal service communication permission for the global administration. Which makes reachable every information inside microservices. I don't know if it is suitable? 

Also if you use keycloack or Okla same permissions occur there. And here UAA is the replacement of Authorization and Authentication point of the system. Why do you think that is not the OAuth way?

**Comment by rifatdover** [comment]
@xetys By the way, I'm not much of an expert on these issues. Forgive me if I make wrong comments.

**Comment by xetys** [comment]
I get your point. That's just some kind of balance between the correct way and the more handsome.

Giving the internal client adminstration permission is easy and solves the problem in one place. As internal clients are used inside the application, that's not that bad.

The more accurate way would be to define a distinct role, or even scope, or even an SpEL expression, done in every single microservice, to limit the permission to this client just to that endpoint. But this would mean a user must touch everything in advance to make this feature working.

The other point is, I don't want to use the UAA user system for the registry, that would mean you need a real user for it. At least for UAA it would cause a cyclic dependency.

**Comment by xetys** [comment]
It's just the service2service communication, one thing where the UAA is good in.

**Comment by ruddell** [comment]
I agree with @xetys that this is an ideal use-case for service-to-service communication.  The way OIDC works is that it duplicated all of the auth logic from the main generator.  With OIDC there isn't the concept of a service account that could have been used.  I also don't think end-users accessing the registry is a normal use-case (normally I would expect admins only)

The main question I see is whether we want the UAA to manage the user accounts or to just have the `admin` account like for JWT apps.

Also thinking about maintenance, 177 lines are easier to maintain than 2600+

**Comment by pascalgrimaud** [comment]
Fixed by https://github.com/jhipster/jhipster-registry/pull/278
