### ISSUE TITLE
Add OIDC support for the JHipster Registry

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-registry#193]
As mentionned in https://github.com/jhipster/generator-jhipster/issues/6519 and also in #148 the JHipster Registry doesn't work with our new OpenID Connect support.

This is of course very important to have this working!

I have started a branch on https://github.com/jhipster/jhipster-registry/tree/oidc-support with a first level of support:

- There is an "oauth2" Spring profile, which is disabled by default -> so by default you have the usual JWT configuration
- When you start the application with the "oauth2" profile, it should work like a JHipster gateway using OpenID Connect

-> at the moment this fails with Keycloak, it seems that my public key is not recognized. I have no idea what I have done wrong here, and I'm totally stuck.

@mraible @danielpetisme could you help me here?

**Comment by danielpetisme** [comment]
Dis you create a `jhipster-registry` client un keycloak? Can you share your
config (via screenshots)?


Le 19 oct. 2017 5:05 PM, "Julien Dubois" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
Yes @danielpetisme I think you need some instructions on running the whole thing:

- Check out `jhipster/jhipster-registry` and use the branch `oidc-support`
- You'll need to build the front-end -> just do `yarn start`, the server won't be started so it will fail, but that will be enough to build the front-end so that's fine
- Run Keycloak: `docker-compose -f src/main/docker/keycloak.yml`
- In Keycloak, there should be the `jhipster-registry` client, see https://github.com/jhipster/jhipster-registry/blob/oidc-support/src/main/docker/realm-config/jhipster-realm.json#L1246 (and I also see it in the Web UI)
- Then start the registry using the `oauth2` Spring profile (I just run it in IDEA and select the profile)
- When go to http://127.0.0.1:8761 you should be automatically redirected to Keycloak, where you should be able to log in
- But you will get an error page saying "We're sorry" with the message `Invalid parameter: redirect_uri`
- And in the Keycloak logs you have stuff like `19:01:17,384 WARN  [org.keycloak.events] (default task-32) type=USER_INFO_REQUEST_ERROR, realmId=jhipster, clientId=null, userId=null, ipAddress=172.18.0.1, error=invalid_token, auth_method=validate_access_token`

**Comment by danielpetisme** [comment]
Weird I don't have the error message and go app to the jhipster registry page. Without more details I think you have a misconfigured keycloak...

I already met the next bug, Once I log into the IdP I enter in an infinite loop (home page -> keycloak -> home page -> repeat). This is due to the `SimplePrincipalExtractor` and this line https://github.com/jhipster/jhipster-registry/blob/oidc-support/src/main/java/io/github/jhipster/registry/web/rest/AccountResource.java#L54
The `SimplePrincipalExtractor` returns a simple String and we try to create a `User` object so a `ClassCastException` is raised thus the front application can't get the user profile and send me to the IdP again where I'm already logged...
To fix the issue I think we can update the method as following:
```
   @GetMapping("/account")
    @Timed
    public ResponseEntity<UserVM> getAccount() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        try{
            UserVM userVM = new UserVM((String) authentication.getPrincipal(),
                authentication.getAuthorities().stream()
                    .map(GrantedAuthority::getAuthority).collect(Collectors.toSet()));
            return new ResponseEntity<>(userVM, HttpStatus.OK);
        } catch (NullPointerException | ClassCastException e){
            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }
```
I simply remove the usage of the `User` class.
it could be a common mistake if someone defines it's own `PrincipalExtractor` which returns something different than a String.

**Comment by jdubois** [comment]
Oh thanks @danielpetisme that helped me a lot: I can now log in!!!! I'll commit the change and link it here.
But then, we still have an issue:

- Create any microservice and launch it
- Log in the registry, using Keycloak
- If you go to Eureka you can see your microservice
- If you go the administration>health page (like other admin pages), select the microservice in the dropbox
-> it will fail with a browser log in window, like if you were not authentified

**Comment by SebastienRene** [comment]
I've looked at this issue. From now, it seems that the problem comes from the microservice.
If I try with a gateway, I can get its metrics. The gateway has the sso activated and not the microservice.
Then if I add in the microservice   
- the OAuth2SsoConfiguration class from the gateway 
- the authorizationHeaderRequestMatcher bean and enable it in MicroserviceSecurityConfiguration
I'm able to have the metrics from the microservice in the registry.
Hope it can help ...

**Comment by jdubois** [comment]
Thanks so much @SebastienRene !! Now did you test before or after? Because I just changed quite a lot of things :-)
I'm having a look again

**Comment by SebastienRene** [comment]
I tested after this commit

**Comment by jdubois** [comment]
Thanks again! I'm testing right now :-) I never thought of this!!

**Comment by jdubois** [comment]
@SebastienRene it doesn't do anything :-(
The error message I have is `java.lang.ClassCastException: org.springframework.security.web.authentication.WebAuthenticationDetails cannot be cast to org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationDetails`

**Comment by SebastienRene** [comment]
I removed the Profil annotation in OAuth2SsoConfiguration in the microservice to test. Did you check that ?

**Comment by jdubois** [comment]
Yes, but still that doesn't work at all :-(

**Comment by danielpetisme** [comment]
Let's assume I have a microservice application named `microservice` when I try to get its metrics I invoke the following url generated
`http://localhost:8761/services/microservice/microservice:875dc69592e3877dd4175610ee174efb/management/metrics`
![capture d ecran 2017-10-23 a 22 18 42](https://user-images.githubusercontent.com/593564/31911212-334100a4-b840-11e7-9ab5-095c5a51791b.png)

As you can see it start with a `/services` jus as required in the `application.yml`
https://github.com/jhipster/jhipster-registry/blob/oidc-support/src/main/resources/config/application.yml#L39

If we add the `services` urlPath to the `OAuth2SecurityConfiguration#configure` method
```
 @Override
    public void configure(HttpSecurity http) throws Exception {
        http
            .csrf()
            .disable()
            .headers()
            .frameOptions()
            .disable()
        .and()
            .sessionManagement()
            .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
        .and()
            .requestMatcher(authorizationHeaderRequestMatcher())
            .authorizeRequests()
            .antMatchers("/api/profile-info").permitAll()
            .antMatchers("/api/**").authenticated()
            .antMatchers("/services/**").authenticated()
            .antMatchers("/management/health").permitAll()
            .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN);
    }
```

The `500` becomes an `401` so it is now a true authentication issue.

**Comment by danielpetisme** [comment]
The problem isn't on the registry but on the services. Actuator endpoints (`/management/health`) have their own security configuration relying on `HTTP Basic`. That's why you have a pop up asking you to log in. This behavior is defined here:
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-security.html
I tried to setup a configuration with `@Order(ManagementServerProperties.ACCESS_OVERRIDE_ORDER)` as described in the link above but I couldn't make it work properly.

Nevertheless, the issue was on security filters chaining so I continued to dig it. I found this StackOverflow post
https://stackoverflow.com/questions/43526821/setting-spring-boot-actuator-with-oauth2-in-the-authorisation-server where the author explained thats since Spring Boot `1.5` Oauth2 resource filter is invoked after the actuator one.
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#oauth-2-resource-filter
The solution is to restore the filter default position `3`.
So simply add `security.oauth2.resource.filter-order: 3` in your YAML and it works.

And because I was sure to already have seen somewhere this configuration I looked into Jhipster code and... the configuration was defined for `uaa` 😄 
https://github.com/jhipster/generator-jhipster/blob/4f62e49476dd9a0dad6d6751086803c7fc65afed/generators/server/templates/src/main/resources/config/_application.yml#L186
https://github.com/jhipster/generator-jhipster/blob/4f62e49476dd9a0dad6d6751086803c7fc65afed/generators/server/templates/src/test/resources/config/_application.yml#L151

I test on a regular monolith,  the metrics are properly collected when no registry is used, not tested with a registry.

I've created the issue https://github.com/jhipster/generator-jhipster/issues/6586 to fix that

**Comment by jdubois** [comment]
Thank you so much @danielpetisme - I'm also spending the evening on this, and I have also a few other findings... I'm trying to aggregate everything!

**Comment by jdubois** [comment]
Oh I got this working!!!!!!!!!!!! I spent so many hours on that! Let me do the changes, because I've modified many things.

**Comment by jdubois** [comment]
I'm not saying my code is perfect, but it should be good enough for a release, and anyway I've spent so many hours on this, it's time to do a release and move on... So release `v3.2.0` is under way.

**Comment by jdubois** [comment]
Closed as https://github.com/jhipster/jhipster-registry/commit/9880e25624baa02f1531e6cfa457a36cf9344387 is merged, and release https://github.com/jhipster/jhipster-registry/releases/tag/v3.2.0 is under way

**Comment by danielpetisme** [comment]
I just have one concern, when I come on thé home page i have a message
saying I'm logged as "Anonymous User". I have to signe out to be able to
sign in correctly.
Do you had the case ?

**Comment by SebastienRene** [comment]
I confirm that add `security.oauth2.resource.filter-order: 3` removes the http basic authentification from the microservice.
Have you tried with a gateway ? I can get the gateway metrics in the registry without adding `.antMatchers("/services/**").authenticated()`. Don't you ?
 I'm not sure this configuration is needed since theses URLs are managed by Zuul in the registry.

**Comment by jdubois** [comment]
- Sorry I broke the unit tests with v3.2.0 so I need to solve that
- @danielpetisme yes I have the same issue :-(
- @SebastienRene you are correct, and I have no idea why it works for the gateway and not the registry!

**Comment by SebastienRene** [comment]
The gateway has `@EnableOAuth2Sso` so requests coming from the registry's Zuul are authorized.

**Comment by jdubois** [comment]
- In fact I didn't break the tests, it was already broken in the previous release... WTF is that??
- @SebastienRene we also have the `@EnableOAuth2Sso`

**Comment by SebastienRene** [comment]
I just pulled generator-jhipster and I have no `@EnableOAuth2Sso` in a new generated microservice.

**Comment by jdubois** [comment]
Oh no, it's only on the gateway and on the registry - that's why they should work the same (but they don't....)

**Comment by danielpetisme** [comment]
@SebastienRene Microservices don't need `@EnableOauth2Sso` because they don't have provide any access toke. They only check the token they receive against the IdP.

**Comment by SebastienRene** [comment]
Yes I see in the JHipter context.

Actually @jdubois they do work the same independently if a add `security.oauth2.resource.filter-order: 3` to both microservice and gateway : I mean if a just log in the registry I can get the metrics from the microservice and the gateway.
But if I go back to the gateway where I was log in previously, even if the home says You are logged in as user "admin", we've got the ClassCastException you had.

In this case, in debug if I put a break point in  the gateway on org.springframework.security.web.access.intercept.FilterSecurityInterceptor, the principal becomes anonymousUser :
org.springframework.security.authentication.AnonymousAuthenticationToken@9055c2bc: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@b364: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: null; Granted Authorities: ROLE_ANONYMOUS

If I log again in the gateway, all calls to the microservice are OK.
