### ISSUE TITLE
Update to jhipster 4.13.2

### ISSUE THREAD

**Issue by filmsolutions** [jhipster/jhipster-registry#223]
##### **Overview of the issue**
Unable to deploy AWS production. jhipster aws throws error aws-sdk not found

##### **Motivation for or Use Case**
I can't use jhipster registry in production. Tried to use npm install aws-sdk uuid progress but no success

##### **Reproduce the error**
clone jhipster from git and run jhipster to update but no success

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I know what you mean -> the AWS sub-gen was corrected in a newer release, so it doesn't work with the current JHipster Registry release.

- That's also a good point for us, on why we need to have modules instead of sub-generators, as they are easier to update
- Unfortunately we have no plan to update the Registry at the moment, as there's far more to do than just updating the sub generator

Of course the temporary fix for you is to force the version of JHipster, (do a manual upgrade of generator-jhipster) and just use it for doing your deployment.

-> we shouldn't do it right now anyway, as we're have a brand new AWS sub-generator being developed, so we need to wait & see until that's finished

**Comment by filmsolutions** [comment]
Just need an help !
./mvnw -Pprod package 
./jhipster-registry-3.4.2.war -spring.profiles.active is not deploying with Prod profile.
In JHipsterRegistryApp.java I added
for(String profile : env.getActiveProfiles()){
     System.out.println(profile);
 }

Output:
swagger
dev
native

means my application is not having a prod profile all togther ?

**Comment by jdubois** [comment]
No there's no real prod profile for the registry (there is one but it does the same thing as dev profile)

**Comment by jdubois** [comment]
It has been upgraded to v4.13.3 in #239
(please note this hasn't been released yet)
