### ISSUE TITLE
base64-secret not working

### ISSUE THREAD

**Issue by abhisheksharma85** [jhipster/jhipster-registry#289]
##### **Overview of the issue**

Registry is not working with base64-secret. I am running registry in production using this config
https://github.com/abhisheksharma85/fs-registry-config
If I leave secret uncomment that I get this warning 
Warning: the JWT key used is not Base64-encoded. We recommend using the `jhipster.security.authentication.jwt.base64-secret` key for optimum security.

If I comment secret and uncomment base64-secret then I get this error
2018-09-06 00:05:51.180 ERROR 26913 --- [           main] i.g.j.registry.JHipsterRegistryApp       : 
----------------------------------------------------------
Your JWT secret key is not configured using Spring Cloud Config, you will not be able to 
use the JHipster Registry dashboards to monitor external applications. 
Please read the documentation at http://www.jhipster.tech/jhipster-registry/

##### **Motivation for or Use Case**

It is a bug, coz as per documentation I am supposed to use base64-secret but it is not working.

##### **Reproduce the error**

Just clone registry and sample config , now comment secret and add base64-secret and provide a base64 encoded secret. No try to run with prod profile

##### **Related issues**

Nope

##### **Suggest a Fix**

We can changes in TokenProvider to handle this bug

##### **JHipster Registry Version(s)**
4.0.1

##### **Browsers and Operating System**
Ubuntu 16.04 LTS

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes -> use "secret" for the moment with the Registry. I will have a look today, maybe we need a specific release.

**Comment by jdubois** [comment]
Oh I get it, in fact the error message "Your JWT secret key is not configured using Spring Cloud Config (...)" is obsolete now.

Let me change this and do a new release, but you can ignore it.

**Comment by abhisheksharma85** [comment]
Thank you Julien for such a quick response.

**Comment by jdubois** [comment]
Hang on, let me test further :-)
I'll delete the last comments to keep the thread clean

**Comment by jdubois** [comment]
After much testing, this works well in `prod` profile: I'm guessing you have some misconfiguration, so let me try to help you.

- If you use both "secret" and "base64-secret", you will use the value from "secret". This is because you could use the JHipster Registry to manage several JHipster applications, made with different JHipster versions, and "base64-secret" has just been released in the last version.
- Our documentation on the JHipster Registry doesn't mention "base64-secret", I'm going to update it just after writing this comment.
- You need to check if you are really using the "prod" profile. The easiest way is to look at the logs, the first line should be `The following profiles are active: prod,composite`. If you're not having this, then you are not in prod profile: can you check this and add a comment here?

**Comment by abhisheksharma85** [comment]
Thanks for this fix. 

Also, I have implemented Two-factor Login and Refresh Token in my gateway for authenticate. I want to submit my contributions. Should I just create a PR for jhipster ?

**Comment by pascalgrimaud** [comment]
@abhisheksharma85 : you should open a ticket at generator-jhipster with full detail so we can understand your proposal and discuss about it

**Comment by jdubois** [comment]
Closing as this looks OK.
@abhisheksharma85 yes thanks for the proposal

**Comment by abhisheksharma85** [comment]
I have submitted proposal

**Comment by jdubois** [comment]
Thanks @abhisheksharma85 !
