### ISSUE TITLE
OAuth2 Gateway Management Broken

### ISSUE THREAD

**Issue by ruddell** [jhipster/jhipster-registry#292]
##### **Overview of the issue**
When attempting to manage the gateway through the JHipster Registry Administration pages, you get a 302 to log in with Keycloak with an invalid_redirect_uri.  OAuth2 microservices work fine.

Originally reported on StackOverflow: https://stackoverflow.com/questions/52258423/jhipster-registry-and-keycloak-cors-error-getting-service-informations

##### **Motivation for or Use Case**
Should work out-of-the-box

##### **Reproduce the error**
Generate an OAuth2 Gateway
```
echo '{ "generator-jhipster": { "promptValues": { "packageName": "com.mycompany.myapp", "nativeLanguage": "en" }, "jhipsterVersion": "5.3.1", "applicationType": "gateway", "baseName": "oauthgway", "packageName": "com.mycompany.myapp", "packageFolder": "com/mycompany/myapp", "serverPort": "8080", "authenticationType": "oauth2", "cacheProvider": "hazelcast", "enableHibernateCache": true, "websocket": false, "databaseType": "sql", "devDatabaseType": "h2Disk", "prodDatabaseType": "mysql", "searchEngine": false, "messageBroker": false, "serviceDiscoveryType": "eureka", "buildTool": "maven", "enableSwaggerCodegen": false, "clientFramework": "angularX", "useSass": true, "clientPackageManager": "npm", "testFrameworks": [], "jhiPrefix": "jhi", "enableTranslation": true, "nativeLanguage": "en", "languages": [ "en" ] } }' > .yo-rc.json
jhipster
``` 
Launch JHipster Registry with `oauth2` profile
Launch Gateway
Navigate to the Loggers page and choose the gateway from the dropdown
In the browser console you can see several CORS errors which are really caused by the redirect URI which uses the gateway's IP instead of localhost.
```
Failed to load http://192.168.0.3:8080/login: Redirect from 'http://192.168.0.3:8080/login' to 'http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth?client_id=web_app&redirect_uri=http://192.168.0.3:8080/login&response_type=code&scope=openid%20profile%20email&state=N7PdJ1' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8761' is therefore not allowed access.
```
##### **Related issues**
Don't think so

##### **Suggest a Fix**
Couldn't figure out a fix

##### **JHipster Registry Version(s)**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by 7uc0** [comment]
Same issue using okta / keycloak oidc

**Comment by pomeisl** [comment]
Same problem with keycloak

**Comment by pascalgrimaud** [comment]
Do you have this problem only with the Registry or with the Gateway too ?

**Comment by 7uc0** [comment]
> Same problem using Keycloak.
> 
> Only with the gateway.
> Administration pages of the registry app and other services (generated as microserivce application) are working fine.

I confirm @szogibalu feedback

**Comment by MetalMiner** [comment]
Hi,
I am facing the same problem. Login works like charm, but accessing metrics or api from another OAuth2 secured service fails with "401". Inspecting the network call shows that the registry does not send any authorization header at all with the calls. So I think the problem is really client related. Something broken with the OAuth2 service? For reference: I am using Keycloak as OIDC provider.

**Comment by MetalMiner** [comment]
I could solve the issue. In `io.github.jhipster.registry.service.ZuulUpdaterService ` you initialize Zuul roots the following way:
`ZuulRouteDTO route = new ZuulRouteDTO(instanceId, "/" +
                    application.getName().toLowerCase() + "/" + instanceId + "/**",
                    null, url, zuulProperties.isStripPrefix(), zuulProperties.getRetryable(), null,
                    instanceInfos.getStatus().toString());`
Problem with this is the following: You set the _sensitiveHeaders_ property to `null`. This will lead to all sensitive headers beeing removed since this is the default. To left the headers unfiltered (which is what we want to achieve) you have to set the _sensitiveHeaders_ property to an empty set:
`ZuulRouteDTO route = new ZuulRouteDTO(instanceId, "/" +
                    application.getName().toLowerCase() + "/" + instanceId + "/**",
                    null, url, zuulProperties.isStripPrefix(), zuulProperties.getRetryable(), Collections.EMPTY_SET,
                    instanceInfos.getStatus().toString());`
