### ISSUE TITLE
[Proposal] Split the config & registry into separate instances

### ISSUE THREAD

**Issue by jd-carroll** [jhipster/jhipster-registry#42]
Is there a reason that both the registry & config servers were combined?  As far as scaling this in a production environment, I think it would be better to separate the config instance(s) from the core registry.  [Not that it would really break anything if it wasn't]

I am still new to Eureka, but I get the sense that we would be able to use the Eureka based registry beyond the current gateway discovery.  Could be completely wrong, not sure, but just thought I would bring it up.

**Comment by jdubois** [comment]
- This is mostly for simplicity, it's easier to have everything in one place than to have 2 servers
- The way it usually works, applications first connect to the config server and then to the registry: you need both workings at the same time anyway, so having 2 different servers will just add up more issues
- In terms of scaling, both needs to be HA (as you can't start your app without both of them), anyway. So, again, splitting this in 2 will just add more complexity and problems.

In terms of performance: both servers have very low usage, so there is no benefits in splitting them. In fact, for "normal usage", it would cost you a lot less to have only one server than two (basically, half the price...). That's why I'd rather put everything in the same place.

Then, if you want to split the existing server, that's currently very easy.

**Comment by jd-carroll** [comment]
Thanks Julien
