### ISSUE TITLE
Cant deploy 6.2.0 to heroku, keeps picking up JDK 8

### ISSUE THREAD

**Issue by neilgrewal** [jhipster/jhipster-registry#467]
##### **Overview of the issue**

Cant deploy the latest registry (v6.2.0) to heroku as it picks up JDK 8 during the deployment rather than JDK 11
##### **Motivation for or Use Case**

I want to be able to click to deploy rather than building it manually and pushing
##### **Reproduce the error**

Click deploy to heroku, fill in 6.2.0 in version
##### **JHipster Registry Version(s)**

6.2.0

##### **Browsers and Operating System**

Mac Catalina

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
I've opened a PR that uses Java 11 in Heroku when clicked on the button. Also it defaults to the most recent jhipster-registry version (6.2.0). However the deployment doesn't work since it seems jhipster-registry gives an out of memory exception even when increased to 512 MB which is the maximum memory in the Heroku free plan. So anybody using this Heroku button will need to use a paid plan with more than 512 MB I think for this to work. :thinking:

**Comment by SudharakaP** [comment]
Disregard my previous comment; I've figured out the problem. It seems that we are specifying unnecessary JVM properties which are automatically added by Heroku; https://devcenter.heroku.com/articles/java-support#adjusting-environment-for-a-dyno-size. When we remove those the deployment works properly. :smile:

**Comment by neilgrewal** [comment]
Awesome! Thanks for the quick feedback, when can we get this merged? :)

**Comment by SudharakaP** [comment]
Hi, you are welcome.

About merging, I have no idea. It depends on the time the reviewer has,
whoever it might be. Hopefully it won't take much time. 😋

But you can always check the changes in the pull request, integrate those
changes to your fork and deploy it from there. 🙃

**Comment by SudharakaP** [comment]
@neilgrewal : Alternatively you can deploy it from the branch in my fork; https://github.com/SudharakaP/jhipster-registry/tree/fix-for-heroku-deployment

**Comment by neilgrewal** [comment]
I went with that same approach after seeing your change, have it running finally!
