### ISSUE TITLE
[FEATURE] Add a deploy to docker cloud button

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-registry#50]
Similar to the deploy to heroku button.

Try it here:

 [![Deploy to Docker Cloud](https://files.cloud.docker.com/images/deploy-to-dockercloud.svg)](https://cloud.docker.com/stack/deploy/?repo=https://github.com/PierreBesson/jhipster-registry/tree/docker-cloud-button)

It would simply require to add a `docker-cloud.yml` file at the root of the repo similar to what we have with the Procfile. On the contrary to what you would think at first, even though it comes from Docker, it is not entirely compatible with the latest docker-compose syntax as it doesn't support `version: '2'`.

**Comment by jdubois** [comment]
I think we need to pay for it... So unless they sponsor us like Heroku or Cloud Foundry, we won't be able to test.

**Comment by PierreBesson** [comment]
@marcelinobadin, As I know you are a docker cloud user, would you see value in this ?

Also Docker Cloud seems to have broken the button with their new ugly UI. (I managed to get the feature back by re-switching to the old UI and re-clicking the button).

**Comment by marcelinobadin** [comment]
Well, since I moved to microservices architecture my challenge was to find a easy way to deploy applications, keep using my continuous integration and automatically scale the application.

On the monolithic version I used to use AWS ElasticBeanstalk which works pretty fine mostly because its scalling abilities.

Now, with the microservices architecture I am mysql, elasticsearch and mongo, also I have the jhipster-registry, and so, using a docker approach makes life easier. But how to deploy, how to scale?

AWS EC2 is pretty cool but demands high effort for configuration. You have to create a cloudformation with autoscalling groups, configuration launcher, S3, a lot of things to make my solution work.

Using docker-compose is too simple and I couldn't find a easy way for auto scalling and continuous integration.

Docker Swarm is pretty cool, I think I need to go further in to it but Docker Cloud as long as I understand is pretty much similar and is working very fine.

I have also tried Heroku and Pivotal Cloud Foundry but gets complicated for my data store layer. For the datastore on this case I had to manage by my self.

On Docker Cloud I could deploy easily my applications and gateway. Easy to integrate to my continuous integration and also I can attach clusters from my own infrastructure for some specific cases. Auto scalling will be complex but manageable. I will have to create a solution for that with some product or customizing a solution using AWS Lambda or something like it.

The new UI from Docker Cloud sucks, I have sent some bugs to them but it still a pain in the ass, I am using only the old interface.

But overall, Docker Cloud for this microservices architecture was the best option for my use cases and needs (and knowledge) and for monolithic Beanstalk is the best.

About to create a button to deploy jhipster-registry I don't see to much value because on Docker Cloud what you will really need is a Stack (something like the docker-compose.yml file). The stack will help you to connect one service to another using hostnames. If you only deploy an application and try to map it on another it seems not to work (I can test this more later, but I had a lot of problems with the hostname and as much as I could learn reading the manuals you need a Stack File to help find your services).

That's my humble opinion as you asked.

And thanks for asking me.

**Comment by PierreBesson** [comment]
Thanks a lot for your reply. I have tested Docker Swarm and although it does work with docker-compose, it is a "do it yourself" cloud platform and is not in itself a complete solution to manage your prod.

Then I think we won't need this button after all so I'm closing this issue.

**Comment by jdubois** [comment]
Thanks @marcelinobadin for sharing your experience on deploying JHipster in prod! We really need this kind of feedback!
